### ISSUE TITLE
Plot Time Series Stations - Turn  On/Off files for viewing

### ISSUE THREAD

**Issue by mattbilskie** [zcobell/MetOceanViewer#42]
There are check boxes next to files when plotting time-series data. If the check box is unchecked can that file not be shown when viewing?

**Comment by zcobell** [comment]
That was the idea, but the feature may be broken. I'll check into it.

**Comment by zcobell** [comment]
@mattbilskie - This is fixed and a new version is posted for download [here](https://github.com/zcobell/MetOceanViewer/releases/tag/v4.4.1).
